[features]
seeds = false
[programs.localnet]
solana_tic_tac_toe = "9163nkVWAADRHwSsK4NsbXEZ7UvqWXTR4inGDfustd5v"
stats = "TicQkEcbikbk4K5LpMthVWhsZNmrJnopA9mcupg5qcr"
[programs.devnet]
solana_tic_tac_toe = "9163nkVWAADRHwSsK4NsbXEZ7UvqWXTR4inGDfustd5v"
stats = "TicQkEcbikbk4K5LpMthVWhsZNmrJnopA9mcupg5qcr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/gr8/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "app/idl/"
